spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
  kafka:
    bootstrap-servers: localhost:9092
    group-id: donuts
    consumer:
      auto-offset-reset: earliest
  embedded:
    kafka:
      brokers:
        property: spring.kafka.bootstrap-servers

aws:
  credentials:
    access-key: access-key
    secret-key: secret-key
  s3:
    bucket: donutBucket
    region: ap-southeast-1