info:
  app:
    version: {project.version}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: public
  kafka:
    bootstrap-servers: localhost:9092
    group-id: donuts
    consumer:
      auto-offset-reset: earliest
  embedded:
    kafka:
      brokers:
        property: spring.kafka.bootstrap-servers

management:
  endpoints:
    web:
      exposure:
        include: info, health, flyway, metrics, caches, prometheus # or '*' for all endpoints
  endpoint:
    info:
      env:
        enabled: true
      java:
        enabled: true
    health:
      show-details: always #alternative: when_authorized

aws:
  credentials:
    access-key: access-key
    secret-key: secret-key
  s3:
    bucket: donutBucket
    region: ap-southeast-1